### PR TITLE
Enhancement/341 Tracker Address config option

### LINKED ISSUE #341: Add tracker request endpoint config option
### Is your enhancement related to a problem? Please describe.

Current state of the plugin, 

The Sophi tracker is requested (out of the box) from `https://cdn.sophi.io/latest/sophi.min.js`  

We want to give users the option to set this string from the plugin settings page so that they can request a dedicated tracker built for them specifically

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Description of the Change

* In the plugin settings page's "Collector settings", added a third item called "Tracker Address".

image
[image link](https://www.screencast.com/t/c31brZr5HK)

* It defaults to "https://cdn.sophi.io/latest/sophi.min.js" as the value but can be changed by a user as desired.
* It was hardcoded in some places, so it is updated in all those places.
* URL validation is added, on an invalid entry, the default value will be set. See the screenshot:

image
[image link](https://www.screencast.com/t/txIM2c2s1Y)

Closes #341

### Alternate Designs

screenshots added above

### Possible Drawbacks

nothing

### Verification Process

1. Visit the `Settings > Sophi.io` page in the WordPress back end.
2. In the plugin settings page's "Collector settings", see a third item called "Tracker Address".
3. Try to save a non-url value and confirm it does not save and the value saved back to the default one.
4. Confirm that the value is appended to the `assets/js/frontend/sophi-tag.js` and it is working fine. <- not sure how to test this step @jeffpaul 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Added - A new tracker request endpoint config option.
> Removed & Changed - Hardcoded tracker endpoint removed and value used from the new tracker request endpoint setting field.

### Credits

Props @YMufleh @faisal-alvi @jeffpaul

### CODE REVIEW

**Comment by jeffpaul** [comment]
@faisal-alvi mind handling the merge conflict here, otherwise this looks good

**Comment by faisal-alvi** [comment]
@jeffpaul conflicts are resolved.

**Comment by YMufleh** [comment]
@faisal-alvi I'm testing this and found a url validation that is invalid but is saved and breaks tracking. 
can you please update the validator to include this case. 


`ht://cdn.sophi.io/latest/sophi.min.js`

**Comment by jeffpaul** [comment]
@YMufleh to confirm, you tried to save `ht://cdn.sophi.io/latest/sophi.min.js` in the `Tracker Address` field and the validation did NOT flag that as invalid and instead saved that into the DB?  If so, we can handle that in a follow-on issue in the next release as that's something that otherwise can be avoided by the current Sophi clients either using the default address or properly adding in the custom Tracker Address provided by the Sophi team.  I don't think we'll want to hold up the 1.3.0 release for this change.

However, if I'm misunderstanding things here, please provide more detail/context so I can help triage... thanks!

**Comment by faisal-alvi** [comment]
@YMufleh we are validating the URLs with the help of PHP's [validating filter](https://www.php.net/manual/en/filter.filters.validate.php): `FILTER_VALIDATE_URL`. A valid URL may not specify the HTTP protocol hence this filter might be passing the URL you've tested. However, if required, we can add another check (along with the existing PHP filter) for `http`/`https` and make its presence mandatory.

**Comment by YMufleh** [comment]
That's correct @jeffpaul @faisal-alvi , 

We're good to add this modification for the next release. 
Thank you

**Comment by YMufleh** [comment]
LGTM

**Pull request merged**
