### PR TITLE
Update to use wp-categories for sectionNames field

### LINKED ISSUE #134: Update sectionNames from breadcrumb to categories
**Is your enhancement related to a problem? Please describe.**
In order to best curate content, Sophi will require that WordPress sends all Categories on a piece of content via the `sectionNames` variable and replace the current data being sent (breadcrumb).

**Describe the solution you'd like**
Update:
```
'sectionNames'   => Utils\get_section_names( Utils\get_post_breadcrumb( $post ) ),
```
to receive Categories.

**Designs**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Rahmon**
### Description of the Change

This change updates the code to send wp-categories for sectionNames field.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Closes: #134 

### Changelog Entry

Changed to send wp-categories in sectionNames field

### CODE REVIEW

**Review by jeffpaul — COMMENTED** [review]
Generally looks about right to me as long as this is gathering all the human-readable names of all Categories and passing along.  Also don't know if its helpful/necessary to pack it all into that single line, but I don't see that as necessary; will defer to @felipeelia formally though.

**Comment by jeffpaul** [comment]
@felipeelia any concerns from your end on this, or good to merge to `develop` to test on the 10uplabs.dev site with the Sophi team?

**Comment by felipeelia** [comment]
> as long as this is gathering all the human-readable names of all Categories

@jeffpaul, if I'm reading the code right, this will send slugs. Should we use `'fields' => 'names'` instead? cc @Rahmon 

> Also don't know if its helpful/necessary to pack it all into that single line, but I don't see that as necessary;

You mean, change only the `'sectionNames'        => ...` line? As we need to check if that is a WP_Error or not, having it in a variable will save us one function call. Or do you mean something else?

**Comment by jeffpaul** [comment]
> @jeffpaul, if I'm reading the code right, this will send slugs. Should we use 'fields' => 'names' instead? cc @Rahmon

Yes, we should be sending `names` and not `slugs`.

> You mean, change only the 'sectionNames' => ... line? As we need to check if that is a WP_Error or not, having it in a variable will save us one function call. Or do you mean something else?

Disregard my comment, I think this is fine to be as-is across multiple lines.

**Comment by Rahmon** [comment]
@jeffpaul @felipeelia I've updated to send `names` instead of `slugs`.

**Comment by jeffpaul** [comment]
@felipeelia I think this looks good, if you agree go ahead and merge so we can test on the 10uplabs site.

**Review by felipeelia — APPROVED** [review]

**Comment by felipeelia** [comment]
@jeffpaul @Rahmon yup, this looks good to me!

**Pull request merged**
