### PR TITLE
Revert "SIT-2708:Update to save the response as a post meta field"

### PR DESCRIPTION
**Pull request by oscarssanchez**
Reverts globeandmail/sophi-for-wordpress#253

### CODE REVIEW

**Comment by Sidsector9** [comment]
**Note:** If this is reverted, we might want to revert PR #282 as well.

**Comment by oscarssanchez** [comment]
Hi @Sidsector9 ,

I believe the revert back of #282 should not bring any issues, since we don't have a `post_id` property anymore, let me know if you think differently. Thanks!

**Comment by Sidsector9** [comment]
@oscarssanchez I may have worded it poorly. I added `post_id` in the transient name as part of PR #282 
If we revert PR #280 , it will remove the usage of post_id, so we might also have to revert PR #282 as well.

**Comment by Sidsector9** [comment]
Okay I just saw you pushed a commit. Looks good, approving 👍

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
