### PR TITLE
SIT-2793: Add hostname and path fields to schema

### LINKED ISSUE #192: SIT-2793: Update Sophi plugin to cm content_update v 2-0-3
Details being tracked in https://voltron.atlassian.net/servicedesk/customer/portal/41/SIT-2793

### PR DESCRIPTION
**Pull request by Rahmon**
### Description of the Change

This PR adds the fields hostname and path to the schema sent to Sophi on CMS updates.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

SIT-2793

### Changelog Entry

Added hostname and path fields to the schema.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Will defer to @dinhtungdu or @felipeelia, but love the idea.

**Review by dinhtungdu — COMMENTED** [review]
I don't have access to the issue so I don't know why we're using canonical URL here, given that with Yoast SEO, the canonical URL can be different from the post permalink. If it's intentional, then this is LGMT.

**Comment by Rahmon** [comment]
@dinhtungdu good catch. I've updated to use the permalink. Could you review it again?

**Review by dinhtungdu — APPROVED** [review]
LGTM!

**Pull request merged**
